#! /usr/bin/env lua

-- Copyright (C) 2015 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-amalgamate.
--
-- dromozoa-amalgamate is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-amalgamate is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-amalgamate.  If not, see <http://www.gnu.org/licenses/>.

local package_loaded = dromozoa_amalgamate_package_loaded
if package_loaded == nil then
  package_loaded = {}
  for k, v in pairs(package.loaded) do
    package_loaded[k] = v
  end
end

local amalgamate = require "dromozoa.amalgamate"

for k, v in pairs(package.loaded) do
  package.loaded[k] = package_loaded[k]
end

local this = amalgamate()
  :setup_arg()
  :setup_searchers()
  :setup_require()
  :setup_exit()
  :eval()

if this.output == nil then
  this:write(io.stdout)
else
  this:write(assert(io.open(this.output, "wb"))):close()
end
